package logbook

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// AppendADIF appends one QSO record to an ADIF file. The writer intentionally
// emits only widely interoperable core fields and stores message text in COMMENT.
func AppendADIF(path string, qso QSO) error {
	if path == "" {
		return fmt.Errorf("empty ADIF path")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	if info, statErr := f.Stat(); statErr == nil && info.Size() == 0 {
		if _, err := f.WriteString("Generated by JTTY-Go<eoh>\n"); err != nil {
			return err
		}
	}
	_, err = f.WriteString(FormatADIF(qso))
	return err
}

func FormatADIF(q QSO) string {
	var b strings.Builder
	add := func(name, value string) {
		if value == "" {
			return
		}
		b.WriteString(fmt.Sprintf("<%s:%d>%s", name, len(value), value))
	}
	addDateTime := func(dateName, timeName string, t time.Time) {
		if t.IsZero() {
			return
		}
		u := t.UTC()
		add(dateName, u.Format("20060102"))
		add(timeName, u.Format("150405"))
	}
	addDateTime("QSO_DATE", "TIME_ON", q.StartUTC)
	addDateTime("", "", time.Time{})
	add("CALL", q.Call)
	add("GRIDSQUARE", q.Grid)
	add("NAME", q.Name)
	if q.PowerWatts > 0 {
		add("TX_PWR", fmt.Sprintf("%.1f", q.PowerWatts))
	}
	add("OPERATOR", q.Operator)
	add("STATION_CALLSIGN", q.StationCallsign)
	add("MY_GRIDSQUARE", q.StationGrid)
	add("BAND", q.Band)
	if q.Frequency > 0 {
		add("FREQ", fmt.Sprintf("%.6f", float64(q.Frequency)/1e6))
	}
	add("MODE", q.Mode)
	add("RST_SENT", q.RSTSent)
	add("RST_RCVD", q.RSTRcvd)
	add("STX_STRING", q.ExchangeSent)
	add("SRX_STRING", q.ExchangeRecv)
	if !q.EndUTC.IsZero() {
		u := q.EndUTC.UTC()
		add("QSO_DATE_OFF", u.Format("20060102"))
		add("TIME_OFF", u.Format("150405"))
	}
	comment := strings.TrimSpace(strings.Trim(strings.Join([]string{q.FirstRXMessage, q.LastRXMessage}, " | "), " |"))
	add("COMMENT", comment)
	b.WriteString("<EOR>\n")
	return b.String()
}
